mongo:
	mkoctfile --mex  -L/usr/lib  -lpthread -lz -lm -ldl -lssl -lcrypto -lmongoc-1.0 -lbson-1.0  mongodb.c -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0
	mv mongodb.mex mongodb_.mex
